# Introducción: 

<div style="text-align: justify">

Chile suele ser comparado con sus países vecinos por el rápido mejoramiento infraestructural y de servicios que ha tenido en las últimas décadas [@PNUD2017] como también por la reducción drástica de la pobreza desde los años noventa [@ministeriodedesarrollosocial_evolucion_2017]. Sin embargo, se ha mantenido en el centro de las discusiones públicas y académicas el problema de los altos niveles de desigualdad socioeconómica [@Flores2019; @oecd_society_2019; @perez_geografia_2020; @PNUD2017], como también el problema de la vulnerabilidad social y situaciones de precariedad que experimenta la mayor parte de la población que reside en Chile [@arcos_invisibility_2016; @oecd_broken_2018; @PNUD2017]. Si bien en el estallido social de 2019 se expresó el malestar de la población chilena frente a las injusticias y a las grandes desigualdades [@ruiz_rebelion_2020], estudios señalan que en Chile los niveles históricos de desigualdad socioeconómica se han mantenido estables [@PNUD2017; @oecd_broken_2018] y ha aumentado la concentración de ingresos del capital en el último tiempo [@flores_desigualdad_2020]. Un reciente informe del *World Inequality Lab* [@chancel_world_2021] sugiere que la desigualdad en Chile ha sido extrema durante los últimos 120 años, con una gran concentración de la riqueza y de ingresos en el 1% más rico de la población. A partir de lo expuesto, es pertinente preguntarse cómo es que se mantienen estos niveles de desigualdad en el tiempo. La desigualdad socioeconómica, como también la pobreza, son fenómenos que se mantienen e intensifican a partir de diversos factores de la vida social [@piketty_distributional_2018]. La línea de investigación de desigualdades subjetivas aborda el problema de los mecanismos psicosociales que legitiman la desigualdad socioeconómica [@kluegel_beliefs_1986]. En este marco, investigaciones han demostrado el efecto que tienen las subjetividades de la población en la legitimación de las desigualdades y en el apoyo al mantenimiento del status quo [@Frei2020a; @hoyt_believing_2021; @kluegel_beliefs_1986; @Mijs2019]. En parte, esta legitimación resulta de las creencias y actitudes negativas hacia la pobreza [@hoyt_believing_2021; @jost_quarter_2019; @lepianka_are_2007; @Lepianka2010]. 

El estudio sobre atribuciones de pobreza y riqueza es un clásico dentro de las investigaciones de creencias de pobreza y desigualdad [@kluegel_beliefs_1986]. Estas se entienden por cómo la gente explica las causas de que haya grupos desaventajados o grupos con grandes comodidades [@Frei2020a]. Tradicionalmente, las atribuciones de pobreza y riqueza se han categorizado en internas y externas, en donde las primeras responsabilizan a las personas por su situación -por ejemplo, explicar la pobreza como consecuencia de la pereza-, mientras que las segundas son explicaciones en que se responsabiliza a la sociedad -por ejemplo, explicar la pobreza como consecuencia del sistema económico- [@pontificiauniversidadcatolicadechile_dimensiones_2018]. Las atribuciones se han relacionado con el apoyo o aversión hacia políticas redistributivas [@kornbluh_exploring_2019; @marquis_when_2021; @Sainz2019], las percepciones sobre la desigualdad [@Schneider2015], la justificación y legitimación de desigualdades, actitudes hacia ricos y pobres [@pontificiauniversidadcatolicadechile_dimensiones_2018], entre otros temas. Las atribuciones de pobreza y riqueza suelen ser tratadas como variable dependiente y se han identificado distintos factores que influyen en que estas varíen. En investigaciones sociológicas suelen destacar las variables sociodemográficas -como la edad o el sexo- y de estatus social -tanto objetivas como subjetivas- [@bucca_merit_2016a; @pontificiauniversidadcatolicadechile_dimensiones_2018]. En general se ha entregado sostén a la hipótesis de interés racional, en donde aquellos de mayor estatus mantienen atribuciones individualistas como forma de legitimar su posición, mientras que los de estatus bajo se oponen a ellas ya que les afecta directamente [@lepianka_are_2007].  Sin embargo, los efectos varían drásticamente dependiendo del contexto y de la forma medición de las atribuciones, y muchas veces se encuentran efectos nulos por parte de estas variables. Por otra parte, se han asociado las creencias meritocráticas con las atribuciones de pobreza [@hoyt_believing_2021; @Madeira2019; @major_ideology_2017], aunque no siempre de manera empírica y sin determinar una clara relación.

Ya desde la investigación de @kluegel_beliefs_1986 en los ochenta se da indicios de que existen elementos referentes a la cultura individualista que podrían afectar más que las variables objetivas en las creencias sobre pobreza. Distintas investigaciones identifican como parte de esta cultura individualista la ideología del mérito, la cual se ha visto que justifica, legitima y mantiene las barreras de clase [@kay_complementary_2003; @piff_shifting_2020]. La meritocracia puede entenderse como un sistema de distribución de recursos y recompensas basado en el mérito individual, siendo el mérito en su concepción original una combinación de talento y esfuerzo [@young_rise_1962]. Ha entrado en discusión que el mérito, como valor y mecanismo generador de juicios [@Araujo2017], se instaló con fuerza en la sociedad chilena [@araujo_desafios_2012; @Araujo2017; @cocina_cinco_2013; @cocina_cree_2013]. El adherir a creencias meritocráticas se posiciona como una opción válida y justa por parte de la población a la hora de ordenar de forma jerárquica a la sociedad, siendo la lógica de justicia de mercado la que más defiende las ideas meritocráticas. De esta forma, la idea de una sociedad meritocrática se convierte en un proyecto común para la población, independiente de la posición política y del estrato socioeconómico [@cocina_cree_2013; @dubet_dilemas_2021]. 

Por su parte, las creencias meritocráticas refieren a las creencias de las personas acerca de cómo operan o debiesen operar los mecanismos meritocráticos en la sociedad. Las creencias meritocráticas se vincula con una mayor preferencia por la desigualdad jerárquica en grupos y con mayores niveles de desigualdad socioeconómica [@major_ideology_2017], como también con la culpabilización de la pobreza. Específicamente, se ha visto que, a mayor percepción meritocrática, mayor culpabilización de la pobreza [@hoyt_believing_2021]. Si bien las atribuciones de carácter interno se han relacionado con el mérito y la idea de justicia meritocrática, muchas veces se da por sentada la relación entre meritocracia y atribuciones internas sin un trabajo empírico previo. Un ejemplo de ello se evidencia en la investigación de @bucca_merit_2016a sobre atribuciones de pobreza en América Latina, en donde reiteradamente se vincula el mérito a las atribuciones internas sin incluir en los análisis indicadores que refieran al mérito o a las creencias meritocráticas. Aunque la evidencia preliminar sugiere que aquellos que muestran mayor afinidad por las creencias meritocráticas tienden a atribuir la pobreza -y la riqueza- a factores más internos que externos, es importante estudiar esta relación de manera empírica, sobre todo en una sociedad con altos niveles de desigualdad socioeconómicos y con un fuerte proyecto meritocrático como lo es la chilena. Además de trabajar con las atribuciones de pobreza como variable dependiente, siendo esta la opción más habitual, se incluye a las atribuciones de riqueza, ya que es considerado como un factor importante a la hora de estudiar la legitimación de desigualdades socioeconómicas [@Lepianka2010]. De lo anterior, se desprende la siguiente pregunta de investigación: 

> ¿Cómo se relacionan las creencias meritocráticas con las atribuciones de pobreza y riqueza? 

Siguiendo a @dubet_repensar_2011, las dos grandes concepciones de la justicia social son la igualdad de posiciones y la igualdad de oportunidades, ambas necesarias a la hora de combatir las tensiones en torno a las desigualdades en la sociedad. La primera busca que las distintas posiciones en la estructura social estén más próximas las unas a las otras. La segunda busca “(…) ofrecer a todos la posibilidad de ocupar las mejores posiciones en función de un principio meritocrático” [@dubet_repensar_2011, pág.11]. Algunas líneas de pensamiento liberal más radical proponen a la meritocracia como el único orden social verdaderamente justo [@bergandres_mas_2019]. La presente investigación discute con la lógica liberal de la justicia de mercado, la cual sostiene que la posición que ocupan los individuos en la jerarquía social es producto de sus esfuerzos y méritos [@lane_market_1986]. Investigaciones de esta línea buscan enfrentar la desigualdad a partir del mejoramiento de la igualdad de oportunidades, bajo la idea de que el mercado opera de manera objetiva, respondiendo únicamente a “las preferencias individuales, con total independencia de las motivaciones y de las apreciaciones de las personas sobre el mérito.” [@rojas_es_2021, pág.24]. Sin embargo, esta lógica obvia la existencia de estructuras que subyacen a estas preferencias y decisiones aparentemente individuales, ya sea por una falta de conciencia estructural, como también puede estar motivado por la necesidad de justificar el sistema [@godfrey_developing_2016].

El omitir los efectos de las posiciones sociales en las trayectorias de los individuos, y pensar en la meritocracia como el principal mecanismo con el que se distribuyen y/o con el que se deberían distribuir los bienes, guarda un lado negativo que es el de legitimar las desigualdades socioeconómicas. Una manera en la que se expresa esta legitimación es mediante la responsabilización y culpabilización de aquellos que se encuentran en una situación desfavorable, como también al explicar las causas de la riqueza a partir del mérito individual. El argumento de la presente investigación es no es deseable que la población perciba que las recompensas se distribuyen a partir de mecanismos meritocráticos, ya que trae como consecuencia el excluir y marginar a grupos de la población, sobre todo a aquellos que ya se encuentran en una posición desfavorable, y legitimar la riqueza al explicar las causas de su posición por factores individuales. En este sentido, las creencias meritocráticas no se oponen a la desigualdad, sino más bien a un cierto tipo de discriminación, las cuales terminan operando como un mecanismo legitimador de las desigualdades socioeconómicas [@hoyt_believing_2021; @Mijs2020]. Para sostener lo anterior, se plantea la siguiente hipótesis general:

> Hipótesis general: Las atribuciones de pobreza y riqueza se explican parcialmente por las creencias meritocráticas

Evidenciar el efecto de las creencias meritocráticas sobre las atribuciones de pobreza y riqueza es un aporte en diferentes aspectos para el estudio de desigualdades subjetivas en Chile, especialmente si se considera que en sociedades desiguales se tienen mayores atribuciones internas [@bucca_merit_2016a] como también se sostienen mayores creencias meritocráticas basadas en el criterio de esfuerzo [@Mijs2019]. Su aporte teórico radica en cuestionar la teoría de justicia de mercado al señalar que las creencias meritocráticas generan consecuencias negativas para la sociedad, específicamente, legitimando las desigualdades socioeconómicas al responsabilizar a los individuos de su propia situación y posición en la sociedad. Debe quedar en claro que la investigación no se opone al marco de igualdad de oportunidades, si no más bien critica el enaltecimiento de esta a partir del criterio meritocrático, como también la omisión de la perspectiva de igualdad de posiciones. De esta manera, es deseable que se generen políticas públicas que actúen sobre la estructura de las posiciones sociales, generando condiciones mínimas y dignas, para luego volver al problema de la igualdad de oportunidades.

En este sentido, el estudio es un aporte al debate público al analizar de manera crítica ideas y valores tan arraigados y aceptados de manera transversal en nuestra sociedad, como lo es el mérito. Es un avance en reconocer la responsabilidad que tienen las creencias meritocráticas de la población en la legitimación de desigualdades, en donde incluso la defensa del mérito puede jugar un rol en justificar que ciertos grupos puedan acceder a derechos sociales mientras que otros más desfavorecidos no. Además, al ser el mérito un valor aceptado transversalmente en los distintos sectores abre la discusión sobre cómo se posicionan los actores a cargo de los cambios sociales, especialmente la izquierda. Inevitablemente se prioriza un marco ideológico al momento de generar políticas sociales y programas, en donde no es indistinto priorizar, por ejemplo, la igualdad de oportunidades meritocrática por sobre la igualdad de posiciones. 

En el ámbito académico, es un aporte en identificar una variable que puede ser central a la hora de explicar la variación en atribuciones de pobreza y riqueza. El distinguir conceptualmente la meritocracia de las atribuciones internas, como también el abordar la relación que ambos fenómenos mantienen, puede aportar a futuros debates e investigaciones en no confundir y/o usar indistintamente ambos conceptos. 

A partir del problema y la pregunta planteados hasta ahora, la presente investigación se propone el objetivo de:

* Analizar la relación entre atribuciones de pobreza y riqueza con las creencias meritocráticas

## Estructura de investigación

<div style="text-align: justify">

El [capítulo 2: Antecedentes](#antecedentes), presenta en el primer apartado una revisión analítica y empírica sobre la conceptualización de las atribuciones de pobreza y riqueza, en donde, además, se discute las formas de medición y operacionalización de la variable en estudios cuantitativos. En el segundo apartado se revisan los antecedentes respecto de la variable independiente, es decir, las creencias meritocráticas. Finalmente, se discute la relación entre creencias meritocráticas y atribuciones de pobreza y riqueza, para luego presentar las hipótesis específicas. 

El [capítulo 3: Datos, variables y métodos](#método), presenta los datos y variables utilizados. Luego se especifican los métodos para realizar el análisis. En el presente estudio se realiza un análisis factorial confirmatorio para la construcción de la variable dependiente e independiente. Luego se realizan modelos de ecuación estructural para analizar la relación entre creencias meritocráticas y atribuciones de pobreza y riqueza.

En el [capítulo 4: Análisis](#análisis) se encuentra el análisis descriptivo, el análisis factorial confirmatorio para la variable dependiente e independiente y los modelos de ecuaciones estructurales que analizan la relación entre creencias meritocráticas y atribuciones de pobreza y riqueza. 

El [capítulo 5: Conclusiones](#conclusiones) retoma los hallazgos encontrados y los hace dialogar con la pregunta e hipótesis planteadas al principio del estudio. A continuación se resumen los principales resultados que muestran soporte para afirmar la tesis central, pero también se indican aquellos puntos que deben ser puestos en duda. Para cerrar se indican las ideas para futuras investigaciones en base a toda la investigación ejecutada. 

