
```{r echo=FALSE}
knitr::opts_chunk$set(out.width="80%", fig.pos = "!ht", out.extra = "")
```

# Antecedentes {#antecedentes}

## Atribuciones de pobreza y riqueza

### Conceptualización y medición de atribuciones

<div style="text-align: justify">

La teoría atribucional se preocupa de estudiar las explicaciones que dan las personas comunes y corrientes, o la población en general, a las causas e implicaciones de ciertos eventos observables [@ross_intuitive_1977]. Desde la psicología social, esta puede ubicarse en la rama de la inferencia causal, la cual trata los juicios y explicaciones de factores que podrían producir cierta situación, a diferencia de la inferencia de rasgos, que se centra en el proceso de las personas de asignar rasgos o características individuales [@heider_psychology_1958]. @weiner_attributional_2011 distinguen tres dimensiones en las atribuciones, siendo estas la de locus, estabilidad y de control. En la primera se distinguen las atribuciones o explicaciones internas -a partir de características individuales- y las externas -a partir de características contextuales o externas al individuo-. La dimensión de estabilidad refiere a cómo se comportan las atribuciones en el tiempo, pudiendo ser estas temporales o estables. La tercera refiere a si las atribuciones que se dan pertenecen a un orden de situaciones controlables por parte del (los) individuo(s), o si son incontrolables. En la presente investigación se prioriza la discusión en torno al concepto de locus.

Desde la tradición de investigación cuantitativa, el estudio sobre atribuciones se ha focalizado en tres constructos principales desarrollados por @feaginj.r_subordinating_1975: (a) explicaciones individuales que atribuyen la pobreza y la riqueza a factores individuales como la irresponsabilidad personal y la falta de esfuerzo, capacidad o talento; (b) explicaciones estructurales que atribuyen la pobreza y la riqueza a factores estructurales como los bajos salarios, la discriminación y la mala calidad de la educación; y (c) explicaciones fatalistas que atribuyen la pobreza y riqueza a la mala suerte, enfermedad y circunstancias desafortunadas [@godfrey_developing_2016]. No obstante, la tercera ha presentado menor consistencia [@bullock_predicting_2003]. En este sentido, las atribuciones suelen estudiarse de manera dicotómica entre atribuciones internas y externas [@heider_psychology_1958; @kluegel_beliefs_1986]. En resumen, las atribuciones internas enfatizan la disposición personal, lo cual ha sido relacionado con elementos legitimadores de las desigualdades sociales, mientras que las externas atribuyen la culpa al entorno social y a las estructuras sociales, asociado a una visión más crítica acerca de la distribución de recursos en la sociedad y sobre las desigualdades [@Schneider2015]. 

Estas dos categorías de atribuciones internas y externas han sido trabajadas de diferentes maneras. Existe cierto consenso en la literatura en torno a la idea de que las atribuciones internas y externas no presentan un carácter estrictamente unidimensional, es decir, que lo interno y lo externo sean dos polos de un mismo continuo [@Frei2020a; @hunt_individual_1996; @osborne_latent_2015a]. De esta forma, las atribuciones pueden ser también una combinación de explicaciones internas y externas[@bucca_merit_2016a; @osborne_latent_2015a; @Frei2020a] lo cual se sostiene bajo la premisa de que las personas pueden mantener distintas visiones e incluso contradictorias y/o incoherentes [@hunt_individual_1996; @kluegel_beliefs_1986]. A esta categoría se le suele denominar atribuciones ambivalentes o mixtas, y la construcción de ella depende en gran medida del método de medición de la variable.

En cuanto a la medición de las atribuciones de pobreza y riqueza, existen dos formas tradicionales de incorporar las atribuciones en las encuestas. En una se presentan las distintas razones que explican las carencias o grandes ventajas de las personas, junto a una escala de respuestas -por ejemplo, una escala likert de acuerdo/desacuerdo- [@pontificiauniversidadcatolicadechile_dimensiones_2018]. En la otra, se presenta una lista de razones que explican las carencias o comodidad de las personas, en la cual se seleccionan dos, una como primera mención -prioritaria- y otra como segunda mención [@bucca_merit_2016a; @Frei2020a]. 

Los estudios de atribuciones de riqueza son escasos, y en la mayoría se suele estudiar junto a las atribuciones de pobreza [@pontificiauniversidadcatolicadechile_dimensiones_2018]. Por su parte, existe una agenda investigativa más amplia para el caso de las atribuciones de pobreza [@cozzarelli_attitudes_2001; @Schneider2015]. Más recientemente se ha ampliado el repertorio de estudios que trabajan conjuntamente las atribuciones de pobreza y riqueza [@bucca_merit_2016a; @Frei2020a; @kreidl_perceptions_2000].

En las investigaciones que trabajan tanto con atribuciones internas como externas, se evidencia el problema de que no existe un consenso en instrumentos, operacionalizaciones y métodos [@pontificiauniversidadcatolicadechile_dimensiones_2018]. Por ejemplo, no existe consenso sobre una escala común para medir los indicadores de las atribuciones de pobreza y riqueza [@pontificiauniversidadcatolicadechile_dimensiones_2018]. Además, con pocas excepciones, las atribuciones de pobreza y riqueza son tratadas como dos variables dependientes por separado. Sin embargo, se ha identificado que tanto las atribuciones internas como externas son factores comunes para la pobreza y riqueza [@pontificiauniversidadcatolicadechile_dimensiones_2018], lo cual permitiría incluir ambas variables en los modelos e identificar patrones comunes a ambos fenómenos. 

Otro de los problemas que se presentan a la hora de estudiar las atribuciones, es que los datos disponibles son escasos, sobre todo al considerar el conjunto de atribuciones de pobreza y riqueza [@pontificiauniversidadcatolicadechile_dimensiones_2018]. Pero además está el problema de medición, en donde, si bien algunos indicadores coinciden en distintas encuestas, no existe un consenso general sobre una escala común [@pontificiauniversidadcatolicadechile_dimensiones_2018]. Esto genera problemas al momento de comparar estudios. 

### Antecedentes de las atribuciones de pobreza y riqueza

#### Consecuencias de las atribuciones de pobreza y riqueza

<div style="text-align: justify">

Las atribuciones de pobreza y riqueza han sido relacionadas con distintos fenómenos sociales, como  el apoyo u oposición a políticas redistributivas [@alesina_fighting_2004; @alesina_preferences_2009; @andersen_social_2015; @benabou_social_2001; @bullock_predicting_2003; @Sainz2020], la percepción y justificación de desigualdades sociales y económicas [@Lepianka2010; @oorschot_blame_2000a; @Schneider2015], actitudes negativas hacia los pobres [@cozzarelli_attitudes_2001], entre otros. 

Las principales conclusiones sobre los efectos de las atribuciones de pobreza y riqueza en los distintos fenómenos sociales mencionados anteriormente, son que el mantener atribuciones internas reduce el apoyo a intervenciones gubernamentales y políticas redistributivas, mientras que las externas aumentan el apoyo [@bullock_predicting_2003]; las atribuciones internas justifican las desigualdades socioeconómicas, mientras que las externas las desafían [@Schneider2015]; y por último, que las atribuciones internas favorecen actitudes negativas hacia personas en situación de pobreza [@hoyt_believing_2021], mientras que las atribuciones externas afectan de manera positiva en las actitudes hacia personas pertenecientes de este grupo social [@cozzarelli_attitudes_2001].

Adicionalmente, se ha destacado desde la psicología social una relación entre las atribuciones de pobreza interna con la deshumanización [@Sainz2020]. La deshumanización se entiende como procesos y circunstancias que niegan aspectos humanos en grupos sociales, los cuales tienen consecuencias de discriminación y de prejuicios degradantes [@dixon_prejudice_2012; @pereira_infrahumanization_2009], como también de legitimación de diferentes tipos de desigualdades [@Sainz2020]. Se ha señalado que la deshumanización tiene efectos estigmatizantes hacia grupos de estatus socioeconómico bajo, como, por ejemplo, contribuyendo a la percepción de que la pobreza es un estado estable y permanente que no puede resolverse mejorando las condiciones socioeconómicas de las familias pobres [@Sainz2020]. 

Los antecedentes para el caso chileno han mostrado un proceso de cambio en las atribuciones de la pobreza y riqueza a partir de la década de los noventa hasta el 2015 en donde aumentan las explicaciones individualistas -atribuciones internas- y disminuyen las atribuciones externas, aunque con una fuerte dimensión ambivalente o combinada entre explicaciones internas y externas [@Frei2020a]. Considerando lo anterior como parte de un proceso de transformaciones sociales más amplio, y en vista de las implicancias y consecuencias de que la población mantenga atribuciones de carácter interno, es que se hace necesario indagar en los principales factores que inciden en las explicaciones de la pobreza y la riqueza.

#### Causas de las atribuciones de pobreza y riqueza

<div style="text-align: justify">

Además de la relación entre las atribuciones de pobreza y riqueza con los diversos fenómenos mencionados en el apartado anterior, existen investigaciones que ahondan en las causas de este fenómeno. Para ello, se han utilizado variables de distinta naturaleza como posibles factores que explicarían el mantener cierto tipo de atribución. En el nivel individual, es posible hacer la distinción entre variables objetivas-estructurales y subjetivas.

Dentro de las variables objetivas, las variables sociodemográficas son comunes a casi todas las investigaciones de atribuciones y actitudes hacia la pobreza. @kluegel_beliefs_1986 nos entregan una aproximación temprana sobre la relación entre variables sociodemográficas, como son la edad, sexo, orientación política e ingreso y variables de creencias sobre la pobreza. En esta investigación sólo la variable de raza tiene efecto en las atribuciones. 

Para el caso chileno, la investigación de @Frei2020a nos muestra que tanto sexo como orientación política no producen diferencias en las atribuciones. No obstante, respecto a la variable edad se observa que los grupos de mayor edad tienen mayor probabilidad de observar atribuciones internas. Cabe mencionar que en esta investigación la forma de medir las atribuciones de pobreza y riqueza es a partir de una lista de opciones, la cual, posterior a un análisis de clases latentes, se categoriza en atribuciones externas, mixtas e internas, trabajándola como una variable ordinal donde las atribuciones internas son el valor más alto, las externas el más bajo y las mixtas un punto intermedio.

En la tradición empírica de estudios sobre estratificación social, existen variables de estatus social objetivo y estatus social subjetivo [@kluegel_beliefs_1986]. Se ha sostenido a partir de variables objetivas que personas de un estatus socioeconómico más alto mantienen atribuciones y creencias individualistas en torno a la desigualdad para legitimizar su superioridad, mientras que aquellos que provienen de estratos socioeconómicos más bajos culpan a la sociedad de su privación ya que perciben mayor rigidez y falta de oportunidades [@hunt_individual_1996; @hunt_race_2004; @kluegel_beliefs_1986; @kreidl_perceptions_2000]. Lo anterior coincidiría con la explicación bajo la perspectiva de legitimación, la cual explica que los grupos sociales aventajados tienen intereses en mantener sus ventajas a través de la autojustificación, mientras que los grupos desaventajados generarían una visión crítica respecto de su propia situación [@kluegel_beliefs_1986; @Mijs2019]. Por su parte, también se ha visto un efecto en variables de estatus subjetivo, en donde a mayor estatus social subjetivo, más atribuciones internas se mantienen [@bucca_merit_2016a].

El que personas de menor estatus y/o en una situación de desventaja mantengan explicaciones externas se le ha denominado **underdog thesis** o tesis de los desvalidos [@robinson_equality_1978], en donde aquellos que se encuentran en una posición desaventajada en la sociedad mantienen una visión más crítica. Además de estudiarse desde el estatus socioeconómico, investigaciones han observado dicho efecto en otros grupos que se encuentran en situaciones de desventaja, como las mujeres y etnias minoritarias [@Madeira2019; @bucca_merit_2016a; @kluegel_beliefs_1986].

Por otra parte, existe evidencia contraria a la tesis de los desvalidos, en donde se ha observado que personas de menos ingresos mantienen atribuciones  de carácter interno -individualista- [@Frei2020a], como también se ha observado que aquellos de clases ocupacionales más altas mantienen más atribuciones externas [@bucca_merit_2016a] aunque estos resultados cuentan con una baja significancia. Frente a esto, se ha sugerido que las personas pobres tienden a subestimar el alcance de su pobreza y desventaja relativa [@cruces_biased_2013] y, en ocasiones, se culpan a sí mismas de sus circunstancias [@mccoy_priming_2007; @Mijs2019; @newman_falling_1999].

Para el caso chileno se observa que quienes pertenecen a quintiles más bajos atribuyen más causas internas a la pobreza y riqueza, mientras que con la educación pasa lo contrario -a mayor educación, más causas internas- [@Frei2020a]. En @bucca_merit_2016a se obtienen resultados diferentes, en donde aquellos con título universitario mantienen explicaciones más estructuralistas. La relación de que a mayor nivel educacional más atribuciones internas rechaza en parte la hipótesis ilustrada, esta es que a mayor nivel educacional más atribuciones de carácter externo. Dichos resultados podrían relacionarse con un mecanismo de autolegitimación de sectores más altos [@Frei2020a]. Cabe mencionar nuevamente que los resultados pueden variar dependiendo de la forma en que se operacionalice las atribuciones de pobreza y riqueza. Para el caso de @bucca_merit_2016a se agrupan las atribuciones de pobreza por separado de las atribuciones de riqueza, en donde en cada una se agrupan las atribuciones en internas, externas y ambivalentes a partir de un criterio teórico, a diferencia de la clasificación empírica realizada en @Frei2020a a partir de un análisis de clases latentes.

Una reflexión importante que surge del estudio de @kluegel_beliefs_1986, es que la baja correlación que se observa en variables objetivas podría deberse a la influencia generalizada de la ideología del individualismo, dimensión que suele ser excluida a la hora de explicar la variación en atribuciones. En este sentido, además de la relación entre las variables anteriormente mencionadas, están las variables de creencias como determinantes de las atribuciones de pobreza y riqueza. Las variables de creencias estudiadas como determinantes de las atribuciones de pobreza y riqueza son creencias de estratificación social [@kluegel_beliefs_1986], experiencia personal en diferentes aspectos -como exposición a la pobreza y experiencia de movilidad social- [@Lepianka2010] y valores e ideología [@Lepianka2010; @Madeira2019]. Dentro de las variables de valores e ideología, destacan las creencias meritocráticas y el mérito como variable explicativa de las atribuciones de pobreza y riqueza [@hoyt_believing_2021; @Lepianka2010; @Madeira2019].

En la siguiente sección se profundiza en torno al concepto de creencias meritocráticas, para luego indagar en su relación con las atribuciones de pobreza y riqueza.

## Creencias meritocráticas

### El principio meritocrático

<div style="text-align: justify">

El concepto de meritocracia, a partir de su aparición en la obra satírica y crítica de @young_rise_1962, ha crecido en popularidad, apareciendo en diferentes espacios de la cotidianidad. De la mano con dicha popularidad, el concepto ha sido objeto de diversas interpretaciones. Esto es algo que ha sido identificado hace ya algún tiempo, siendo reconocida la meritocracia por @SEN2000 como un concepto de poca claridad. El no tratar detalladamente el concepto de meritocracia, puede presentar problemas que obstaculicen la investigación empírica y la posterior comparación entre estudios. De esta forma, en un sentido amplio, es posible entender a la meritocracia como un orden social que basa la distribución de los recursos a partir del mérito individual. A su vez, el mérito opera a partir de los criterios de esfuerzo y talento [@young_rise_1962]. 

El principio meritocrático ha sido catalogado como el principal mecanismo utilizado por las democracias para mantenerse en equilibrio y justificar las desigualdades socioeconómicas [@bell_meritocracy_1972; @duru-bellat_merite_2009; @lipset_social_1959; @torres_meritocracia_2021]. Es común encontrar en discursos de autoridades y en la cultura y entretenimiento la promoción de la meritocracia, en el sentido de que cualquiera que sea la posición social de un sujeto al nacer, la sociedad debería ofrecer suficientes oportunidades y movilidad para que el "talento" se combine con el "esfuerzo" para "llegar a la cima" [@littler_meritocracy_2017]. Así, desde presidentes de diferentes países [@littler_meritocracy_2017] hasta autoridades locales de distintos sectores [@cocina_cinco_2013], la meritocracia se ha convertido en la gran promesa para transformar a la sociedad en una más justa y democrática. 

El incrementar la movilidad social y promover la igualdad de oportunidades basado en la meritocracia se enmarca en la agenda política liberal igualitaria, a partir de la cual proliferaron investigaciones enfatizando que los principios meritocráticos no se aplican de manera correcta o en justa medida [@Mijs2020]. Desde este enfoque, el problema no sería la desigualdad misma, si no los mecanismos que la legitiman. Tal como menciona @Mijs2019, la meritocracia no se opone a la inequidad sino más bien a ciertos tipos de discriminación -y otros mecanismos de distribución no meritocráticos-.

Han surgido críticas a la idea de meritocracia como un principio distributivo justo, en cuanto respalda un sistema competitivo, lineal y jerárquico en el que, por definición, ciertas personas deben quedar atrás [@littler_meritocracy_2017]. Por otra parte, se ha argumentado que la igualdad de oportunidades como idea fuerza de la meritocracia, no implica necesariamente que una sociedad sea más justa [@cocina_cree_2013]. En este sentido, podría considerarse más bien como una condición necesaria pero no suficiente para que un orden social sea justo [@cocina_cree_2013]. Considerando que la meritocracia no se opone a las desigualdades sociales y que más bien sirve como un mecanismo que legitima un orden jerárquico en la sociedad, es que surgen estudios enfocados en las creencias meritocráticas de la población.

### Las creencias meritocráticas en las ciencias sociales

<div style="text-align: justify">

Parte de la discusión reciente sobre el concepto de las creencias meritocráticas se ha enfocado en su definición conceptual y su operacionalización. Se ha abordado la confusión que genera el término creencias -**beliefs**- meritocráticas, en vista de que algunos autores utilizan el concepto como las percepciones que se tienen de los mecanismos meritocráticos que operan en la sociedad, mientras que otros dan más énfasis al aspecto normativo, refiriéndose a cómo debiesen funcionar -preferencias- estos mecanismos [@Frei2020a]. 

La falta de claridad conceptual sobre lo que se entiende por creencias meritocráticas, ha generado el problema de no tener una base empírica para la investigación de la meritocracia. Para facilitar el trabajo empírico en torno al ambiguo término de creencias meritocráticas, surge la propuesta de distinguir entre las percepciones y preferencias meritocráticas [@castillo_meritocracia_2019a]. Las percepciones meritocráticas hacen referencia a cómo las personas creen que funcionan los mecanismos meritocráticos en una sociedad en específico, mientras que las preferencias meritocráticas refieren a cómo estos deberían ser y funcionar en la sociedad [@castillo_meritocracia_2019a]. Esta conceptualización se enmarca en la perspectiva subjetiva del estudio de la meritocracia, en donde esta última se compone de las perspectivas normativas -preferencias- y las descriptivas -percepciones- [@castillo_meritocracia_2019a]. La presente investigación se centra con más fuerza en la dimensión de las percepciones meritocráticas, tal como se verá en las hipótesis más adelante planteadas.

Además del problema conceptual sobre percepciones y preferencias meritocráticas, se ha discutido sobre la aplicación de las dos dimensiones que componen a la meritocracia -talento y esfuerzo- en distintas investigaciones [@Castillo2020]. En algunos casos se trabajan las creencias meritocráticas de manera unidimensional, como por ejemplo en la investigación de [@Mijs2019], en donde se da mayor énfasis al esfuerzo en el trabajo por sobre el talento. No obstante, se ha comprobado empíricamente que el constructo de meritocracia se compone a partir de la asociación entre talento y esfuerzo [@Castillo2020], por lo que trabajar con una sola dimensión puede significar sesgos en la investigación.

En ciertas ocasiones, investigaciones han incluido elementos de creencias no-meritocráticas en la operacionalización de las creencias meritocráticas, asumiendo una escala continua en donde en un extremo se ubican elementos no meritocráticos, mientras que en el otro extremo elementos meritocráticos [@kunovich_systems_2007; @newman_false_2015]. En este sentido, el rechazo a mecanismos no meritocráticos, como el tener éxito a partir de la posición aventajada de la familia o a partir de los contactos sociales, implicaría un mayor apoyo a mecanismos meritocráticos. Al ser sometido a escrutinio empírico, se ha establecido que factores no meritocráticos no están necesariamente relacionados a factores meritocráticos [@Castillo2020]. De esta manera, es conveniente incluir factores no meritocráticos en las investigaciones empíricas sobre la meritocracia, pero no reducirlos al mismo continuo, sino trabajando ambos elementos como independientes. 

### Relación de la meritocracia con las creencias sobre desigualdad y sobre la pobreza

<div style="text-align: justify">

Uno de los problemas identificados en las investigaciones a la hora de trabajar los conceptos de meritocracia/mérito y atribuciones de pobreza y  riqueza, es que en ocasiones se usa indistintamente el concepto de mérito para las atribuciones internas, como es el caso de la investigación “Merit and blame in unequal societies: Explaining Latin Americans’ beliefs about wealth and poverty” de @bucca_merit_2016a. Si bien ambos conceptos pertenecen al área de estudios de creencias sobre desigualdades sociales, e incluso en ciertas operacionalizaciones comparten conceptos, no obstante, es necesario distinguir entre la ideología meritocrática generalizada, y una expresión de creencias sobre ciertos grupos sociales como aquellos en desventaja o con grandes riquezas.

La creencia en la ideología meritocrática se considera una ideología central que justifica el sistema precisamente porque asume que es justo e implícitamente culpa de las disparidades económicas a la falta de capacidad o motivación individual, más que a factores sistémicos [@jost_antecedents_2005]. La meritocracia ha sido conceptualizada como un principio de justicia distributiva que permitiría a la gente creer que se vive en una sociedad justa aún en sociedades altamente desiguales [@Mijs2019]. De esta manera, cumple un rol importante como mecanismo de legitimación de desigualdades sociales y promotor de una jerarquía social ordenada por grupos sociales en distintos niveles [@castillo_meritocracia_2019a].

@dubet_dilemas_2021, siguiendo un razonamiento marxista, señala que "Lo que explica por qué hay valores falsos en Chile no es el desprecio de clase. Hay desprecio de clase porque hay valores falsos. Es decir, el sistema económico fabrica a los pobres, y luego es necesario un sistema simbólico que justifique el hecho de que existen los pobres." (pág.492-493) Si se considera la evidencia sobre las consecuencias de mantener atribuciones de pobreza internas, es posible que estas se relacionen de alguna manera con lo que el autor llama **desprecio de clase**, en donde las atribuciones operarían como una expresión de sistemas de valores y creencias, mientras que la meritocracia operaría como el **sistema simbólico**. Además, debido a la desigualdad socioeconómica y a los altos niveles de autoidentificación con las clases medias en la sociedad chilena [@espinoza_que_2008], es posible que los grupos sociales explicados -esto es, la pobreza y la riqueza- se perciban como distintos a la situación propia de la mayoría de la población, e incluso como grupos sociales marginales. 

### Antecedentes en la relación entre meritocracia y atribuciones de pobreza y riqueza

<div style="text-align: justify">

En la investigación de @lepianka_are_2007 sobre atribuciones y creencias de la pobreza se evidencia un primer acercamiento a la relación entre creencias meritocráticas y atribuciones de pobreza. En esta investigación la forma de medir las atribuciones es una lista de cinco opciones, en donde se debe escoger dos menciones. Se utilizan cinco constructos que agrupan las variables causales, siendo estas: conciencia de la existencia de pobreza, experiencia personal de desventaja, valores y creencias, características sociodemográficas y características contextuales (nacionales). 

Dentro del conjunto de variables independientes sobre los valores y creencias se identifica como uno de los indicadores el "respaldo al principio de mérito como mecanismo de distribución justo". Se observa que aquellos que adhieren con mayor fuerza a este valor mantienen más atribuciones internas. Sin embargo, esta relación y los niveles de significancia varían drásticamente entre países y regiones, como también al controlar por otras variables de valores y creencias.  Por otra parte, aquellos que mantienen creencias no meritocráticas tienen más probabilidades de atribuir la pobreza al mal funcionamiento del sistema distributivo, y menos probabilidades de ver la pobreza como causada internamente [@lepianka_are_2007].

Posteriormente, en la investigación de @Lepianka2010 sobre atribuciones de pobreza, se incluyeron otras variables en torno a valores e ideología. Las variables del estudio que se relacionan con la meritocracia son (1) “adherencia” al mérito como justo, y (2) la ética del trabajo (PWE por sus siglas en inglés). El mérito como justo se extrae de la pregunta acerca de los elementos que son importantes para que una sociedad sea considerada como justa. A partir de esta pregunta, los encuestados debieron responder el grado de acuerdo o desacuerdo con la frase de “Reconocer a las personas por sus méritos”. Se concluye que a medida que la gente respalda con más fuerza el principio de mérito como justicia, es más probable que se atribuya la pobreza a la pereza antes que a causas estructurales. Por otro lado, respecto a la segunda variable, se concluye que un mayor respaldo a la ética del trabajo (PWE) se relaciona con una mayor propensión a atribuir la pobreza a la ociosidad individual y una menor inclinación a ver la miseria como causada por factores externos, y especialmente la injusticia social.

En una línea similar, se ha estudiado la relación de la meritocracia -bajo la forma de las variables de creencias legitimadoras de estatus (SLB por sus siglas en inglés) y PWE- con actitudes hacia grupos marginados -principalmente a partir de criterios étnicos y de género- [@Madeira2019; @major_ideology_2017]. Se concluye que las creencias meritocráticas cumplen un rol legitimador sobre las desigualdades entre grupos sociales. De manera más específica, se señala que la meritocracia descriptiva -percepciones- está relacionada negativamente con los resultados psicológicos y conductuales intergrupales, mientras que la meritocracia prescriptiva -preferencias- no lo está [@Madeira2019]. De hecho, en el estudio de @Madeira2019, se señala que mayores niveles de preferencia meritocrática tienen un menor efecto en actitudes negativas hacia grupos desfavorables -en este caso hacia las mujeres-, como también que favorecen la aceptación de políticas sociales de defensa del mérito diseñadas para lograr una mayor igualdad intergrupal en el lugar de trabajo (por ejemplo, discriminación positiva) y una mayor oposición a las políticas que violan principios meritocráticos.

El reciente estudio de @hoyt_believing_2021 evidencia que a mayor percepción meritocrática, más se culpabiliza a aquellos en pobreza. A su vez, esta culpabilización actúa como mediadora entre la percepción meritocrática y las actitudes negativas hacia la pobreza. 

A modo de síntesis, la literatura recolectada hasta la fecha sobre creencias meritocráticas y atribuciones de pobreza y riqueza carecen de tres aspectos importantes: trabajar tanto las atribuciones de pobreza como de riqueza, analizar las atribuciones externas y una operacionalización sistemática del concepto de creencias meritocráticas.

Considerando que mayores niveles de percepción meritocrática se ha relacionado con una dimensión legitimadora de las desigualdades socioeconómicas [@castillo_meritocracia_2019a] y con actitudes negativas hacia grupos sociales marginalizados [@Madeira2019], se plantean las siguientes hipótesis específicas

> $H_1:$ A mayor percepción de meritocracia, mayores serán las atribuciones internas hacia la pobreza y la riqueza.

> $H_2:$ A mayor percepción de meritocracia, menores serán las atribuciones externas hacia la pobreza y la riqueza. 

