# Conclusiones {#conclusiones}

<div style="text-align: justify">

El desarrollo de la presente investigación buscó responder a la pregunta ¿Cómo se relacionan las creencias meritocráticas con las atribuciones de pobreza y riqueza? Para responder esta pregunta, se destacan dos pasos del análisis. En un primer momento, se resolvió el problema de medición para las variables dependientes -atribuciones de pobreza y riqueza-, e independientes -creencias meritocráticas-. Para la variable dependiente, se establece las atribuciones internas de la pobreza forman un constructo junto a las variables internas de la riqueza, lo cual ocurre de la misma forma para las atribuciones externas. Esto coincide con lo planteado en [@pontificiauniversidadcatolicadechile_dimensiones_2018]. Por su parte, en los indicadores utilizados para la variable independiente, se distinguieron cuatro factores, siendo estos de percepción meritocrática, preferencia meritocrática, percepción no meritocrática y preferencia no meritocrática. Si bien las percepciones meritocráticas se sitúan en el núcleo de la investigación al ser parte de las hipótesis 1 y 2, el considerar dentro de los modelos multivariados los otros tres factores sobre creencias enriquece los hallazgos. 

La hipótesis general de esta investigación plantea que las atribuciones de pobreza y riqueza se explican parcialmente por las creencias meritocráticas. Los resultados a partir de los modelos estructurales confirman sólo en parte esta hipótesis. En el modelo en que se analizan los factores de las atribuciones internas, destacan las percepciones meritocráticas con un coeficiente mayor al de todas las otras variables. Esto demuestra que las percepciones meritocráticas cumplen un rol importante al momento de explicar las atribuciones internas, en donde mientras más se cree que la sociedad funciona efectivamente a partir de criterios meritocráticos, más se responsabiliza a los individuos de su propia situación, ya sea sobre un grupo que se encuentra en una posición desaventajada, o sobre grupos que disfrutan grandes comodidades. Lo anterior confirma lo planteado por la hipótesis general, como también por la hipótesis específica 1, es decir, que mayor percepción de meritocracia, mayores serán las atribuciones internas hacia la pobreza y la riqueza.

Por su parte, la hipótesis específica 2, la cual plantea que a mayor percepción de meritocracia menores serán las atribuciones externas hacia la pobreza y la riqueza, no se cumple. En los modelos que trabajan las atribuciones externas como variable dependiente, se observa que en un principio las percepciones sí tenían un efecto negativo y significativo sobre las atribuciones externas. Sin embargo, al incluir creencias no meritocráticas en el modelo, el efecto de las percepciones meritocráticas desaparece. En el último modelo se ve que, de los cuatro factores de creencias meritocráticas y no meritocráticas, las únicas variables que tienen un efecto sobre las atribuciones externas son las percepciones y preferencias no meritocráticas. Más específicamente, quienes perciben que en la sociedad se sale adelante al tener padres ricos o buenos contactos, presentan más atribuciones externas sobre la pobreza y la riqueza. Por su parte, quienes prefieren que en la sociedad se salga adelante por tener padres ricos o buenos contactos, mantienen menos atribuciones externas. Que las creencias no meritocráticas sean más explicativas que las creencias meritocráticas sobre las atribuciones externas pueden deberse a que existe cierto consenso transversal en la población de que los factores adscriptivos o de origen en la obtención de recompensas no son deseables para las sociedades modernas [@castillo_meritocracia_2019a]. Por otra parte, recordemos que las atribuciones externas se han relacionado con una visión más crítica acerca de la sociedad [@Schneider2015]. De esta forma, el percibir más mecanismos distributivos injustos o no deseables se vincula de forma directa con una visión crítica, mientras que el preferirlos se vincula directa, pero de manera inversa con esta visión crítica. 

Otros hallazgos destacables de la investigación son que ni educación ni ingresos tienen un efecto significativo tanto en atribuciones internas como externas. Por su parte, sí se encontraron resultados significativos en variables sociodemográficas. Los resultados para la variable de sexo coinciden con la tesis de los desvalidos, en donde mujeres mantienen menos atribuciones internas y más atribuciones externas. Por su parte, también se observó un efecto positivo y significativo de edad sobre las atribuciones internas. Si bien en las investigaciones de atribuciones los resultados del efecto de la edad suelen coincidir con la tesis de los desvalidos [@bucca_merit_2016a; @gijsberts_legitimation_2002], también se ha observado lo contrario, en donde a mayor edad más atribuciones externas [@niemela_perceptions_2008]. A raíz de los hallazgos de la investigación sobre la variable edad, se recomienda para futuras investigaciones trabajar la variable edad en rangos etarios, para ver el efecto específico de cada grupo y observar si existe algún efecto sobre las atribuciones externas.

Un paso importante en la lucha contra la pobreza y la desigualdad es mejorar las creencias y actitudes hacia personas en desventaja socioeconómica [@davis_bringing_2020; @hoyt_believing_2021] y generar conciencia sobre las causas de la riqueza en países con altos niveles de desigualdad socioeconómica. Estudios sugieren que se culpa cada vez más a los pobres de su desgracia y se elogia los éxitos de los ricos por su mérito personal [@Mijs2019]. La presente investigación añade que son las creencias, más que la posición en la que uno se encuentre en la sociedad, lo que determina esta forma de pensar.

Al inicio de la investigación se plantea que quienes atribuyen los resultados económicos a fallas y deficiencias individuales pueden deberse a una falta de conciencia estructural, como también por la motivación en justificar el sistema [@godfrey_developing_2016]. Considerando que se rechazan las hipótesis de interés racional y se encuentra mayor soporte para variables de percepciones y creencias meritocráticas y no meritocráticas, se hace necesario en el contexto chileno fomentar y facilitar la información empírica sobre desigualdades estructurales, y sobre avances en materia de desigualdades subjetivas. Tal como se ha visto en otros estudios, el entregar información sobre cómo operan las estructuras sociales tiene un efecto en las creencias [@Mijs2018]. Por otro lado, se identifica que la agenda liberal da sostén a las creencias meritocráticas en investigaciones como la de @rojas_es_2021, por lo que es importante fomentar una agenda crítica sobre los impactos de las creencias meritocráticas.

Más allá de lo que @hayes_twilight_2012 denomina la "ley de hierro de la meritocracia" que es la contradicción interna del principio meritocrático, en donde la misma meritocracia produce las condiciones para que su cometido sea imposible de cumplirse [@page_merito_2013; @torres_meritocracia_2021], investigaciones como la presente que evidencien los efectos directos que trae el percibir que la sociedad opera de manera meritocrática ayudan a derribar mitos o, como lo llama @dubet_dilemas_2021, valores falsos, lo cual legitima desigualdades y generar actitudes negativas hacia personas desaventajadas económicamente.

La presente investigación cuenta con diversas limitaciones, de las cuales a su vez surgen ideas y propuestas para futuras investigaciones. En primer lugar, los resultados no son aplicables a la realidad de todo el país, en cuanto no son datos representativos de la población chilena. Además, sería deseable que se analizara la relación entre creencias meritocráticas y atribuciones con datos más actuales, en vista de los grandes cambios que ha experimentado la sociedad chilena a partir de las movilizaciones del 2019. En cuanto a la medición de las atribuciones de pobreza y riqueza, en el proceso de investigación se identificó a los indicadores que refieren a la mala suerte o suerte como pertenecientes a un factor latente aparte. Esto reanima el debate acerca de las atribuciones fatalistas, y que rol deberían ocupar en los estudios de desigualdad subjetiva. Sería conveniente incluir más indicadores fatalistas para profundizar su estudio desde una perspectiva cuantitativa, como también 

Junto al problema representatividad y de medición de atribuciones, se abre la discusión respecto a las variables explicativas que fueron utilizadas. Debido a diversas complejidades que surgieron durante la realización del estudio, no pudieron incluirse más variables exógenas de control. En este sentido, variables como la identificación política o el tipo de ocupación podrían haber entregado otros hallazgos. Por último, se identificó un mal ajuste en el análisis factorial confirmatorio para las variables de creencias meritocráticas y no meritocráticas. Ello puede haber conducido a algunos errores en los resultados de los modelos multivariados, por lo que es necesario revisar nuevas formas de operacionalizar los indicadores independientes, y revisar otras formas de medición para futuras encuestas. 

Los resultados de la investigación que muestran una relación positiva entre percepciones meritocráticas y atribuciones internas, como también de creencias no meritocráticas sobre atribuciones internas y externas, sugieren el incluir variables de creencias y valores como condicionantes de las atribuciones de pobreza y riqueza. De lo anterior se abren nuevas líneas a estudiar, como modelos de mediación entre creencias meritocráticas y no meritocráticas, atribuciones y distintos fenómenos, como, por ejemplo, el apoyo a políticas redistributivas. Por otra parte, a partir de las limitaciones mencionadas, surgen nuevas interrogantes en torno a la medición y conceptualización de conceptos del área de las desigualdades subjetivas. En el contexto de una sociedad que se encuentra cambiando a un ritmo acelerado, es importante adaptarse a sus problemas y conceptos más contingentes, como también el perfeccionar las técnicas utilizadas para responder a las preguntas que surgen. 

