#
# This model specification was automatically generated by Onyx
#
library(lavaan);
modelData <- read.table(DATAFILENAME, header = TRUE) ;
 model<-"
! regressions 
   AI=~1.0*atrib_pob_1
   AI=~p2_*atrib_pob_3
   AI=~p3_*atrib_riq_1
   AI=~p4_*atrib_riq_3
   AE=~1.0*atrib_pob_4
   AE=~p6_*atrib_pob_5
   AE=~p7_*atrib_riq_4
! residuals, variances and covariances
   atrib_riq_1 ~~ p8_*atrib_riq_3
   atrib_pob_1 ~~ 0.54446742760636*atrib_pob_1
   atrib_pob_3 ~~ 0.273204625080092*atrib_pob_3
   atrib_riq_1 ~~ 0.72307158961676*atrib_riq_1
   atrib_riq_3 ~~ 0.668554031422075*atrib_riq_3
   atrib_pob_4 ~~ 0.0460375784073552*atrib_pob_4
   atrib_pob_5 ~~ 0.676495753002186*atrib_pob_5
   atrib_riq_4 ~~ 0.781946233330296*atrib_riq_4
   AI ~~ p44_*AI
   AE ~~ p45_*AE
   AI ~~ p46_*AE
! means
   AI~0*1;
   atrib_pob_1~0*1;
   atrib_pob_3~0*1;
   atrib_riq_1~0*1;
   atrib_riq_3~0*1;
   AE~0*1;
   atrib_pob_4~0*1;
   atrib_pob_5~0*1;
   atrib_riq_4~0*1;
";
result<-lavaan(model, data=modelData, fixed.x=FALSE, missing="FIML");
summary(result, fit.measures=TRUE);